import{a as w,S as v,i as c}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function L(t,r,s){return(await w.get("https://pixabay.com/api/",{params:{key:"50311128-48dd02331c2e5a3f7eb5afcac",q:t,page:r,per_page:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const d=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function S(t){const r=t.map(s=>{const{webformatURL:a,largeImageURL:e,tags:o,likes:i,views:g,comments:h,downloads:b}=s;return`
      <li class="gallery-item">
        <a href="${e}"><img class="gallery-image" src="${a}" alt="${o}"/></a>
        <div class="stats">
          <p><span>Likes</span><span>${i}</span></p>
          <p><span>Views</span><span>${g}</span></p>
          <p><span>Comments</span><span>${h}</span></p>
          <p><span>Downloads</span><span>${b}</span></p>
        </div>
      </li>
        `}).join("");d.insertAdjacentHTML("beforeend",r),q.refresh()}function C(){d.innerHTML=""}function B(){p.style.visibility="visible"}function M(){p.style.visibility="hidden"}function $(){m.style.visibility="visible"}function f(){m.style.visibility="hidden"}const O=document.querySelector(".form"),P=document.querySelector(".load-more");let n,l=1;const u=15;O.addEventListener("submit",t=>{t.preventDefault(),f(),C(),n=t.target.elements["search-text"].value.trim(),n&&(l=1,y(n))});P.addEventListener("click",t=>{f(),l++,y(n),x()});async function y(t){B();try{const r=await L(t,l,u),s=r.hits;s&&s.length>0?(S(s),l>=Math.ceil(r.totalHits/u)?c.show({title:"ℹ️",message:"We're sorry, but you've reached the end of search results.",messageColor:"white",titleColor:"white",backgroundColor:"#4CAF50",position:"topRight"}):$()):c.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",titleColor:"white",backgroundColor:"#ef4040",position:"topRight"})}catch(r){console.error(r)}finally{M()}}function x(){const t=document.querySelector(".gallery-item");t&&setTimeout(()=>{scrollBy({top:t.getBoundingClientRect().height*2,left:0,behavior:"smooth"})},200)}
//# sourceMappingURL=index.js.map
