import{a as S,S as $,i as s}from"./assets/vendor-CrlV4O_2.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q="ВАШ_PIXABAY_API_KEY",E="https://pixabay.com/api/",v=15;async function f(r,n=1){const a=`${E}?key=${q}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${v}`;try{return(await S.get(a)).data}catch(t){throw console.error("Ошибка при запросе к Pixabay:",t),t}}const g=document.querySelector(".gallery"),m=document.querySelector(".js-load-more"),y=document.querySelector(".js-loader"),R=new $(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});images;function h(r){const n=r.map(({webformatURL:a,largeImageURL:t,tags:e,likes:o,views:c,comments:P,downloads:w})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${t}">
        <img class="gallery-image" src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${c}</p>
        <p><b>Comments:</b> ${P}</p>
        <p><b>Downloads:</b> ${w}</p>
      </div>
    </li>
  `).join("");g.insertAdjacentHTML("beforeend",n),R.refresh()}function B(){g.innerHTML=""}function p(){y.hidden=!1}function b(){y.hidden=!0}function A(){m.hidden=!1}function l(){m.hidden=!0}const L=document.querySelector(".form"),M=document.querySelector(".js-load-more");let d="",i=1,u=0;L.addEventListener("submit",_);M.addEventListener("click",D);async function _(r){r.preventDefault();const a=new FormData(L).get("search-text").trim();if(a===""){s.error({message:"Please enter a search query",position:"topRight"});return}d=a,i=1,u=0,B(),l();try{p();const t=await f(d,i);if(t.hits.length===0){s.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u=t.totalHits,h(t.hits),t.totalHits>15?A():l()}catch(t){console.error(t),s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}}async function D(){if(i+=1,(i-1)*15>=u){l(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}try{p();const r=await f(d,i);h(r.hits);const n=document.querySelector(".gallery .gallery-item").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"}),i*15>=u&&(l(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){console.error(r),s.error({message:"Error loading more images. Please try again.",position:"topRight"})}finally{b()}}
//# sourceMappingURL=index.js.map
